### ISSUE TITLE
Mobile User Agent Loop

### ISSUE THREAD

**Issue by 0xlildoudou** [c0dejump/HExHTTP#5]
Hi @c0dejump,

A very useful tool!

I needed to modify it during a mission by adding user agent tests. I saw that this need is in the TODO list of the project.
I propose my "dirty" modifications in the project fork in the "mobile-ua" branch.

https://github.com/0xlildoudou/HExHTTP/tree/mobile-UA

Mobile User agent source file: https://gist.githubusercontent.com/hendrik3ka/72056a3a0f18369e75617648a6014c05/raw/2c1223de7f36fc90f25d12a7f552cd51bd14b0a9/Mobile%2520UA%2520(User-Agent)
rename "mobile-user-agent.txt" on ./modules/user-agents/

I apologize in advance for the "dirty" code, but I'd be delighted to collaborate on a more optimized solution :)

**Comment by c0dejump** [comment]
Hello,

Thanks for your comment !

Great work, thanks for the help ! I'll look at it in detail as soon as I have a bit of time :)
